### ISSUE TITLE
Clearing cache & block sync state

### ISSUE THREAD

**Issue by grod220** [prax-wallet/prax#207] opened 2024-10-03 13:09 UTC
When clearing cache, the last block synced status does not clear until a new block is synced. This can cause feelings of unresponsiveness. In case of mainnet, genesis state sync can take some time so it accentuate this feeling. Example:

https://github.com/user-attachments/assets/d8626292-c949-418c-ae92-26ce7071d61e

Likely need to explicitly reset the chrome.storage.local value for lastBlockSynced when issuing a cache clear action.

**Comment by TalDerei** [comment] 2024-10-14 14:27
duplicate of https://github.com/penumbra-zone/web/issues/1496. 

previous offline discussions suggest the remediation may be more involved, but I will investigate.

**Comment by TalDerei** [comment] 2024-10-14 15:47
[chrome.runtime.reload()](https://github.com/prax-wallet/prax/blob/main/apps/extension/src/wallet-services.ts#L92) restarts the extension by terminating and reloading the background service worker and injected content scripts. But reloading the webpage directly causes a redirect to the **"Connect to Penumbra"** page (see https://github.com/penumbra-zone/web/issues/1496). As L pointed out, restarting the background worker breaks all the content scripts, and the constrained single-threaded service worker blocks the listeners responsible for initializing the injected content script.

Wouldn't refactoring the [service worker lifecycle](https://github.com/penumbra-zone/web/issues/1790) automatically resolve this issue as a side-effect? The only additional modification would be to the [promise](https://github.com/prax-wallet/prax/blob/main/apps/extension/src/wallet-services.ts#L89) in the message listener by updating it with:
`await Promise.allSettled([localExtStorage.remove('params'), indexedDb.clear(), chrome.storage.local.remove('fullSyncHeight')]);`

**Comment by grod220** [comment] 2024-10-15 10:04
Yes, I think that `allSettled()` line would resolve the issue and can be done now

**Comment by TalDerei** [comment] 2024-10-15 11:46
> Yes, I think that `allSettled()` line would resolve the issue and can be done now

even with that line, it will immediately display a "[data objects could not be cloned causing transactions to fail](https://github.com/penumbra-zone/web/issues/1495)" error. Then, if you try refreshing the screen, it redirects to the "Connect to Penumbra" page – see video example in https://github.com/penumbra-zone/web/issues/1496.

**Closed** 2024-10-22 06:46 UTC
Labels: bug
